contact_links:
    - name: 📃 Documentation Issue
      url: https://github.com/Feetwings/Frontend/issues/new
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: 🤔 Questions and Help
      url: https://github.com/Feetwings/Frontend/discussions/new
      about: This issue tracker is not for support questions.
